[phases.setup]
nixPkgs = ["nodejs_20", "bun", "openssl"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "npx prisma generate && npx prisma db push && node server.js"
