@echo off
echo Parando servidor...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr ":3000"') do taskkill /F /PID %%a 2>nul
echo Limpando cache...
rmdir /s /q .next 2>nul
echo Iniciando servidor...
bun x next dev -p 3000
