import { AGENT_MEMORY_BRIDGE_ENDPOINTS } from './types';

export const MYTHOS_AGENT_PROFILE = {
  id: 'mythos',
  name: 'Mythos',
  label: 'First official external agent',
  image: '/agents/mythos.png',
  route: '/mythos',
  summary:
    'External agent structured for context, observability, skills, tasks, and verifiable memory on CongChain.',
  counts: {
    skills: 168,
    memoryProvidersBeforeCongChain: 8,
    memoryProvidersWithCongChain: 9,
    llmProviders: 28,
    messagePlatforms: 19,
    languageServers: 26,
    toolFiles: 76,
  },
  identity: {
    namespace: 'mythos',
    lineage: 'Hermes-compatible fork',
    position: 'Independent CongChain external agent',
    compatibility:
      'Hermes compatibility remains available only as a legacy adapter layer. Mythos writes use source=mythos, contentType=mythos_*, and an isolated Mythos vault by default.',
    evolution:
      'The next identity phase can replace inherited Hermes naming with Mythos-native runtime, docs, skills, and distribution without changing the CongChain bridge contract.',
  },
  contracts: [
    {
      name: 'Context Engine',
      status: 'key adapter ready',
      detail:
        'Selects high-value turns before compression and stores them as authenticated Mythos memory.',
    },
    {
      name: 'Observability',
      status: 'key adapter ready',
      detail:
        'Records tool calls, sessions, and task results as an auditable trail without secrets.',
    },
    {
      name: 'Blockchain Skill',
      status: 'compat ready',
      detail:
        'The legacy vault contract is replaced by Authorization Bearer cog_live_* for production use.'
    },
    {
      name: 'Identity Separation',
      status: 'mythos namespace',
      detail:
        'Inherited Hermes behavior is documented as compatibility only; the active agent identity, vault, source, and content types are Mythos-native.',
    },
  ],
  endpoints: {
    health: AGENT_MEMORY_BRIDGE_ENDPOINTS.health,
    writeMemory: AGENT_MEMORY_BRIDGE_ENDPOINTS.writeMemory,
    listMemories: AGENT_MEMORY_BRIDGE_ENDPOINTS.listMemories,
    verifyMemory: AGENT_MEMORY_BRIDGE_ENDPOINTS.verifyMemory,
    readMemory: AGENT_MEMORY_BRIDGE_ENDPOINTS.readMemory,
    readProof: AGENT_MEMORY_BRIDGE_ENDPOINTS.readProof,
  },
  requiredEnv: [
    {
      name: 'CONGCHAIN_API_URL',
      value: 'https://cognchain-program-production.up.railway.app',
      secret: false,
    },
    {
      name: 'CONGCHAIN_API_KEY',
      value: 'cog_live_...',
      secret: true,
    },
    {
      name: 'CONGCHAIN_AGENT_ID',
      value: 'mythos-local',
      secret: false,
    },
  ],
  safety: [
    'The key authenticates reads and writes for the external agent vault.',
    'Content containing API keys, secrets, private keys, or signed payloads is blocked.',
    'Saved memory does not sign, schedule, buy, sell, or move funds.',
    'On-chain/ZK states are explicit and only appear active when really persisted.',
    'Hermes-compatible code paths must not write into the Mythos vault unless source=mythos is explicitly selected.',
  ],
} as const;

export type MythosAgentProfile = typeof MYTHOS_AGENT_PROFILE;

export const MYTHOS_SKILL_CATEGORIES = [
  {
    id: 'congchain',
    label: 'CongChain',
    count: 2,
    summary: 'Official skills for verifiable memory, audit, and bridge workflows.',
  },
  {
    id: 'development',
    label: 'Dev',
    count: 18,
    summary: 'Code, debugging, tests, PRs, APIs, and repository review.',
  },
  {
    id: 'research',
    label: 'Research',
    count: 13,
    summary: 'Research, papers, search, OSINT, and domain intelligence.',
  },
  {
    id: 'agent',
    label: 'Agents',
    count: 7,
    summary: 'Orchestration, subagents, Codex, Mythos, and migrations.',
  },
  {
    id: 'mlops',
    label: 'MLOps',
    count: 39,
    summary: 'Models, inference, evaluation, vectors, and fine-tuning.',
  },
  {
    id: 'productivity',
    label: 'Productivity',
    count: 18,
    summary: 'Docs, notes, workspace, PDF, presentations, and automation.',
  },
  {
    id: 'media',
    label: 'Creative',
    count: 22,
    summary: 'Design, images, video, music, diagrams, and content.',
  },
] as const;

export const MYTHOS_CAPABILITY_GROUPS = [
  {
    id: 'memory',
    label: 'Memory providers',
    count: 9,
    headline: 'Where Mythos can store and retrieve context.',
    explanation:
      'Memory providers connect the agent to history, embeddings, vaults, and verifiable memory. CongChain acts as the verifiable/on-chain-ready provider, separate from traditional memory systems.',
    items: [
      'CongChain',
      'byterover',
      'hindsight',
      'holographic',
      'honcho',
      'mem0',
      'openviking',
      'retaindb',
      'supermemory',
    ],
    howToUse: [
      'Create a key in API Keys.',
      'Set CONGCHAIN_API_KEY in the Mythos environment.',
      'Enable the CongChain provider to save auditable memory.',
      'Use external providers only when you need search, embeddings, or memory outside CongChain.',
    ],
    safety:
      'Memory must not store secrets, private keys, seed phrases, signed payloads, or data that can move funds.',
  },
  {
    id: 'llm',
    label: 'LLM providers',
    count: 28,
    headline: 'Models Mythos can use to reason and execute tasks.',
    explanation:
      'LLM providers are connectors to different model backends. They let Mythos choose the best engine for cost, speed, reasoning, code, vision, or long context.',
    items: [
      'OpenAI',
      'Anthropic',
      'Google Gemini',
      'DeepSeek',
      'Mistral',
      'Groq',
      'Together',
      'Fireworks',
      'OpenRouter',
      'xAI',
      'Z.ai',
      'NVIDIA',
      'MiniMax',
      'Qwen',
      'Cohere',
      'Perplexity',
      'Azure OpenAI',
      'AWS Bedrock',
      'Vertex AI',
      'Ollama local',
    ],
    howToUse: [
      'Choose the provider by task type: code, research, cost, speed, or context.',
      'Add the provider API key to the Mythos environment.',
      'Set a default model for the agent.',
      'Use CongChain to record which model generated each important memory.',
    ],
    safety:
      'Providers may require paid keys. Never paste API keys into memories, public prompts, or saved outputs.',
  },
  {
    id: 'platforms',
    label: 'Platforms',
    count: 19,
    headline: 'Channels where Mythos can talk or receive work.',
    explanation:
      'Platforms are message adapters. They connect the agent to chats, communities, automations, and external interfaces.',
    items: [
      'Discord',
      'Telegram',
      'Slack',
      'WhatsApp',
      'Matrix',
      'X/Twitter',
      'Reddit',
      'GitHub',
      'Email',
      'Web chat',
      'CLI',
      'QQBot',
      'Teams',
      'Google Chat',
      'IRC',
      'LINE',
      'SimpleX',
      'MS Graph',
      'Webhook',
    ],
    howToUse: [
      'Choose the platform where the agent will operate.',
      'Configure that platform token or bot credentials in the Mythos runtime.',
      'Define which events may become CongChain memory.',
      'Start in read-only or test mode before allowing automatic replies.',
    ],
    safety:
      'External channels should use minimum permissions. CongChain records context, but must not expose bot tokens or sensitive conversations without consent.',
  },
  {
    id: 'lsp',
    label: 'LSPs',
    count: 26,
    headline: 'Language-aware code understanding.',
    explanation:
      'LSPs are language servers. They help Mythos understand symbols, errors, references, types, and code structure before suggesting changes.',
    items: [
      'Python',
      'TypeScript',
      'Go',
      'Rust',
      'C/C++',
      'Bash',
      'YAML',
      'Lua',
      'PHP',
      'OCaml',
      'Dockerfile',
      'Terraform',
      'Dart',
      'Haskell',
      'Julia',
      'Clojure',
      'Nix',
      'Zig',
      'Gleam',
      'Elixir',
      'Prisma',
      'Kotlin',
      'Java',
      'Vue',
      'Svelte',
      'Astro',
    ],
    howToUse: [
      'Open a project in Mythos.',
      'Let the language server detect symbols and diagnostics.',
      'Use code skills to plan, test, and review.',
      'Save important decisions to CongChain when there is technical handoff.',
    ],
    safety:
      'LSPs understand code, but destructive commands still require human review.',
  },
  {
    id: 'tools',
    label: 'Tool files',
    count: 76,
    headline: 'Internal tools that expand what the agent can do.',
    explanation:
      'Tool files include helpers, connectors, adapters, and utilities. Not every file is exposed directly to the model, but all of them are part of the operational kit.',
    items: [
      'Terminal controlado',
      'Leitura de arquivos',
      'Busca em repo',
      'Web search',
      'Browser tools',
      'Git helpers',
      'Kanban',
      'Dashboards',
      'Observability',
      'Image generation',
      'Video generation',
      'Google Meet',
      'Spotify',
      'Disk cleanup',
      'Context engine',
      'Model routing',
    ],
    howToUse: [
      'Choose the skill first.',
      'The skill guides which tools should be used.',
      'Mythos runs tools according to the environment permissions.',
      'Relevant results can become verifiable memory in CongChain.',
    ],
    safety:
      'Tools with write, network, automation, or cleanup powers need clear limits and explicit permission.',
  },
] as const;

export const MYTHOS_FEATURED_SKILLS = [
  {
    id: 'congchain-memory',
    name: 'CongChain Memory Bridge',
    category: 'congchain',
    path: 'optional-skills/blockchain/congchain',
    status: 'key ready',
    level: 'oficial',
    useCase:
      'Save Mythos memory to CongChain with hash, owner, isolated vault, and secret blocking.',
    bestFor: 'Use when an external agent needs to record verifiable context.',
    command: 'mythos skill use optional-skills/blockchain/congchain',
  },
  {
    id: 'congchain-forge',
    name: 'CongChain Forge',
    category: 'congchain',
    path: 'skills/software-development/congchain-forge',
    status: 'ready',
    level: 'oficial',
    useCase:
      'Create technical plans and record development decisions connected to the CongChain vault.',
    bestFor: 'Use when Mythos helps with code, architecture, or technical handoff.',
    command: 'mythos skill use skills/software-development/congchain-forge',
  },
  {
    id: 'systematic-debugging',
    name: 'Systematic Debugging',
    category: 'development',
    path: 'skills/software-development/systematic-debugging',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Diagnose bugs through hypotheses, evidence, minimal tests, and traceable fixes.',
    bestFor: 'Use when something broke and needs investigation without guessing.',
    command: 'mythos skill use skills/software-development/systematic-debugging',
  },
  {
    id: 'codebase-inspection',
    name: 'Codebase Inspection',
    category: 'development',
    path: 'skills/github/codebase-inspection',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Read repository structure, locate important flows, and answer with technical references.',
    bestFor: 'Use before changing a large or unfamiliar project.',
    command: 'mythos skill use skills/github/codebase-inspection',
  },
  {
    id: 'test-driven-development',
    name: 'Test Driven Development',
    category: 'development',
    path: 'skills/software-development/test-driven-development',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Turn requirements into tests, implement, and validate changes with lower risk.',
    bestFor: 'Use for sensitive features or refactors that must not break behavior.',
    command: 'mythos skill use skills/software-development/test-driven-development',
  },
  {
    id: 'rest-graphql-debug',
    name: 'REST / GraphQL Debug',
    category: 'development',
    path: 'optional-skills/software-development/rest-graphql-debug',
    status: 'optional',
    level: 'optional',
    useCase:
      'Investigate REST and GraphQL APIs with headers, auth, schemas, errors, and contracts.',
    bestFor: 'Use when an external integration returns 401, 403, 500, or wrong data.',
    command: 'mythos skill use optional-skills/software-development/rest-graphql-debug',
  },
  {
    id: 'arxiv',
    name: 'Arxiv Research',
    category: 'research',
    path: 'skills/research/arxiv',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Search papers, summarize contributions, and compare methods carefully.',
    bestFor: 'Use for technical research and validation of AI, crypto, or science ideas.',
    command: 'mythos skill use skills/research/arxiv',
  },
  {
    id: 'domain-intel',
    name: 'Domain Intelligence',
    category: 'research',
    path: 'optional-skills/research/domain-intel',
    status: 'optional',
    level: 'optional',
    useCase:
      'Analyze domain, product, competitors, positioning, and public signals.',
    bestFor: 'Use before creating narrative, landing pages, or market strategy.',
    command: 'mythos skill use optional-skills/research/domain-intel',
  },
  {
    id: 'subagent-driven-development',
    name: 'Subagent Driven Development',
    category: 'agent',
    path: 'skills/software-development/subagent-driven-development',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Break work into smaller agents, review deliverables, and integrate results.',
    bestFor: 'Use when a large task can be safely parallelized.',
    command: 'mythos skill use skills/software-development/subagent-driven-development',
  },
  {
    id: 'openclaw-migration',
    name: 'OpenClaw Migration',
    category: 'agent',
    path: 'optional-skills/migration/openclaw-migration',
    status: 'optional',
    level: 'optional',
    useCase:
      'Plan migration and compatibility between OpenClaw, Mythos, and external agents.',
    bestFor: 'Use when connecting another agent to the same CongChain contract.',
    command: 'mythos skill use optional-skills/migration/openclaw-migration',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'productivity',
    path: 'skills/note-taking/obsidian',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Organize notes, context, links, and local memory as a vault.',
    bestFor: 'Use when the agent needs to turn work into navigable knowledge.',
    command: 'mythos skill use skills/note-taking/obsidian',
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    category: 'productivity',
    path: 'skills/productivity/google-workspace',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Work with Docs, Sheets, Drive, and productivity materials.',
    bestFor: 'Use for reports, spreadsheets, handoffs, and operational organization.',
    command: 'mythos skill use skills/productivity/google-workspace',
  },
  {
    id: 'evaluation',
    name: 'Model Evaluation',
    category: 'mlops',
    path: 'skills/mlops/evaluation/lm-evaluation-harness',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Evaluate models, benchmarks, and output quality with repeatable criteria.',
    bestFor: 'Use to compare providers or measure improvement before switching models.',
    command: 'mythos skill use skills/mlops/evaluation/lm-evaluation-harness',
  },
  {
    id: 'qdrant',
    name: 'Qdrant Vector Memory',
    category: 'mlops',
    path: 'optional-skills/mlops/qdrant',
    status: 'optional',
    level: 'optional',
    useCase:
      'Use a vector database for semantic search, memory, and context retrieval.',
    bestFor: 'Use when Mythos needs to retrieve knowledge by similarity.',
    command: 'mythos skill use optional-skills/mlops/qdrant',
  },
  {
    id: 'architecture-diagram',
    name: 'Architecture Diagram',
    category: 'media',
    path: 'skills/creative/architecture-diagram',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Turn technical architecture into an explainable and reviewable diagram.',
    bestFor: 'Use to explain CongChain, agents, memory bridge, or product flows.',
    command: 'mythos skill use skills/creative/architecture-diagram',
  },
  {
    id: 'popular-web-designs',
    name: 'Popular Web Designs',
    category: 'media',
    path: 'skills/creative/popular-web-designs',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Generate visual direction and UI references for pages and dashboards.',
    bestFor: 'Use to refine Mythos, Marketplace, or Agent Hub design.',
    command: 'mythos skill use skills/creative/popular-web-designs',
  },
] as const;

export const MYTHOS_CATEGORY_SKILL_INDEX = {
  congchain: [
    'CongChain Memory Bridge',
    'CongChain Forge',
  ],
  development: [
    'Systematic Debugging',
    'Codebase Inspection',
    'Test Driven Development',
    'REST / GraphQL Debug',
    'GitHub Code Review',
    'GitHub PR Workflow',
    'GitHub Issues',
    'GitHub Repo Management',
    'Node Inspect Debugger',
    'Python Debugpy',
    'Requesting Code Review',
    'Writing Plans',
    'Spike',
    'Plan',
    'Debugging Mythos TUI Commands',
    'Mythos Agent Skill Authoring',
    'Subagent Driven Development',
    'CongChain Forge',
  ],
  research: [
    'Arxiv Research',
    'Domain Intelligence',
    'Blogwatcher',
    'LLM Wiki',
    'Polymarket',
    'Research Paper Writing',
    'Bioinformatics',
    'Drug Discovery',
    'DuckDuckGo Search',
    'Gitnexus Explorer',
    'OSINT Investigation',
    'Parallel CLI',
    'SearxNG Search',
  ],
  agent: [
    'Subagent Driven Development',
    'Claude Code',
    'Codex',
    'Mythos Agent',
    'OpenCode',
    'Blackbox',
    'OpenClaw Migration',
  ],
  mlops: [
    'Model Evaluation',
    'Weights & Biases',
    'HuggingFace Hub',
    'Llama.cpp',
    'vLLM',
    'Audiocraft',
    'Segment Anything',
    'DSPy',
    'Qdrant Vector Memory',
    'Chroma',
    'FAISS',
    'Pinecone',
    'Guidance',
    'Instructor',
    'LLaVA',
    'Modal',
    'PEFT',
    'PyTorch Lightning',
    'Stable Diffusion',
    'Whisper',
    'Axolotl',
    'TRL Fine-Tuning',
    'Unsloth',
  ],
  productivity: [
    'Obsidian',
    'Google Workspace',
    'Notion',
    'Linear',
    'Airtable',
    'Maps',
    'Nano PDF',
    'OCR and Documents',
    'PowerPoint',
    'Teams Meeting Pipeline',
    'Canvas',
    'Here Now',
    'Memento Flashcards',
    'Shop App',
    'Shopify',
    'SiYuan',
    'Telephony',
    'AgentMail',
  ],
  media: [
    'Architecture Diagram',
    'Popular Web Designs',
    'ASCII Art',
    'ASCII Video',
    'Baoyu Comic',
    'Baoyu Infographic',
    'Claude Design',
    'ComfyUI',
    'Creative Ideation',
    'Design MD',
    'Excalidraw',
    'Humanizer',
    'Manim Video',
    'P5.js',
    'Pixel Art',
    'PreTeXt',
    'Sketch',
    'Songwriting and AI Music',
    'TouchDesigner MCP',
    'Blender MCP',
    'Concept Diagrams',
    'Meme Generation',
  ],
} as const;

export const MYTHOS_UNIQUE_IDENTITY_PILLARS = [
  {
    id: 'provable-memory-passport',
    name: 'Provable Memory Passport',
    signal: 'Every important memory carries source, agent ID, skill context, hash routes, and safety metadata.',
    enterpriseValue:
      'Teams can inspect what the agent remembered, where it came from, and whether it is safe to reuse.',
  },
  {
    id: 'skill-governed-execution',
    name: 'Skill-Governed Execution',
    signal: 'Work starts from a declared skill category instead of an invisible generic prompt.',
    enterpriseValue:
      'Operators can choose the right capability before execution and audit which skill shaped the outcome.',
  },
  {
    id: 'memory-constitution',
    name: 'Memory Constitution',
    signal: 'Anti-secret, no-funds, no-signed-payload, and human-review rules travel with each write.',
    enterpriseValue:
      'Security teams get a readable policy boundary before Mythos becomes part of real workflows.',
  },
  {
    id: 'cross-model-continuity',
    name: 'Cross-Model Continuity',
    signal: 'Mythos can record model, provider, skill, and task context so work can continue across engines.',
    enterpriseValue:
      'Companies can route between model providers without losing the operational memory trail.',
  },
  {
    id: 'external-agent-vault',
    name: 'External Agent Vault',
    signal: 'Each API key, source, and agent ID writes into an isolated logical vault.',
    enterpriseValue:
      'A business can separate Mythos, Hermes, OpenClaw, Eliza, and future agents without mixing records.',
  },
  {
    id: 'boardroom-audit-packet',
    name: 'Boardroom Audit Packet',
    signal: 'The page exposes setup, payload, bridge status, capabilities, and safety posture in one review surface.',
    enterpriseValue:
      'Technical leaders can review the agent as infrastructure, not just as a chat interface.',
  },
] as const;

export type MythosSkillCategory = (typeof MYTHOS_SKILL_CATEGORIES)[number];
export type MythosFeaturedSkill = (typeof MYTHOS_FEATURED_SKILLS)[number];
export type MythosUniqueIdentityPillar = (typeof MYTHOS_UNIQUE_IDENTITY_PILLARS)[number];
