import { AGENT_MEMORY_BRIDGE_ENDPOINTS } from './types';

export const MYTHOS_AGENT_PROFILE = {
  id: 'mythos',
  name: 'Mythos',
  label: 'Primeiro agente externo oficial',
  image: '/agents/mythos.png',
  route: '/mythos',
  summary:
    'Agente externo estruturado para contexto, observabilidade, skills, tarefas e memoria verificavel na CongChain.',
  counts: {
    skills: 168,
    memoryProvidersBeforeCongChain: 8,
    memoryProvidersWithCongChain: 9,
    llmProviders: 28,
    messagePlatforms: 19,
    languageServers: 26,
    toolFiles: 76,
  },
  contracts: [
    {
      name: 'Context Engine',
      status: 'precisa adaptar key',
      detail:
        'Seleciona turnos de alto valor antes da compressao e grava como memoria Mythos autenticada.',
    },
    {
      name: 'Observability',
      status: 'precisa adaptar key',
      detail:
        'Registra tool calls, sessoes e resultados de tarefa como trilha auditavel, sem segredos.',
    },
    {
      name: 'Blockchain Skill',
      status: 'compat parcial',
      detail:
        'Skill existente precisa trocar vault antigo por Authorization Bearer cog_live_*.'
    },
  ],
  endpoints: {
    health: AGENT_MEMORY_BRIDGE_ENDPOINTS.health,
    writeMemory: AGENT_MEMORY_BRIDGE_ENDPOINTS.writeMemory,
    listMemories: AGENT_MEMORY_BRIDGE_ENDPOINTS.listMemories,
    verifyMemory: AGENT_MEMORY_BRIDGE_ENDPOINTS.verifyMemory,
    readMemory: AGENT_MEMORY_BRIDGE_ENDPOINTS.readMemory,
    readProof: AGENT_MEMORY_BRIDGE_ENDPOINTS.readProof,
  },
  requiredEnv: [
    {
      name: 'CONGCHAIN_API_URL',
      value: 'https://cognchain-program-production.up.railway.app',
      secret: false,
    },
    {
      name: 'CONGCHAIN_API_KEY',
      value: 'cog_live_...',
      secret: true,
    },
    {
      name: 'CONGCHAIN_AGENT_ID',
      value: 'mythos-local',
      secret: false,
    },
  ],
  safety: [
    'A key autentica escrita e leitura do vault do agente externo.',
    'Conteudo com API keys, secrets, private keys ou signed payloads e bloqueado.',
    'Memoria salva nao assina, nao agenda, nao compra, nao vende e nao move fundos.',
    'On-chain/ZK ficam explicitos: somente aparecem como ativos quando forem realmente persistidos.',
  ],
} as const;

export type MythosAgentProfile = typeof MYTHOS_AGENT_PROFILE;

export const MYTHOS_SKILL_CATEGORIES = [
  {
    id: 'congchain',
    label: 'CongChain',
    count: 2,
    summary: 'Skills oficiais para memoria verificavel, auditoria e bridge.',
  },
  {
    id: 'development',
    label: 'Dev',
    count: 18,
    summary: 'Codigo, debug, testes, PRs, APIs e revisao de repositorios.',
  },
  {
    id: 'research',
    label: 'Research',
    count: 13,
    summary: 'Pesquisa, papers, busca, OSINT e inteligencia de dominio.',
  },
  {
    id: 'agent',
    label: 'Agents',
    count: 7,
    summary: 'Orquestracao, subagentes, Codex, Mythos e migracoes.',
  },
  {
    id: 'mlops',
    label: 'MLOps',
    count: 39,
    summary: 'Modelos, inferencia, avaliacao, vetores e fine-tuning.',
  },
  {
    id: 'productivity',
    label: 'Produtividade',
    count: 18,
    summary: 'Docs, notas, workspace, PDF, apresentacoes e automacao.',
  },
  {
    id: 'media',
    label: 'Criativo',
    count: 22,
    summary: 'Design, imagens, video, musica, diagramas e conteudo.',
  },
] as const;

export const MYTHOS_CAPABILITY_GROUPS = [
  {
    id: 'memory',
    label: 'Memory providers',
    count: 9,
    headline: 'Onde o Mythos pode guardar e recuperar contexto.',
    explanation:
      'Providers de memoria conectam o agente a historico, embeddings, vaults e memoria verificavel. A CongChain entra como o provider on-chain/verificavel, separado dos providers tradicionais.',
    items: [
      'CongChain',
      'byterover',
      'hindsight',
      'holographic',
      'honcho',
      'mem0',
      'openviking',
      'retaindb',
      'supermemory',
    ],
    howToUse: [
      'Crie uma key em API Keys.',
      'Configure CONGCHAIN_API_KEY no ambiente do Mythos.',
      'Ative o provider CongChain para salvar memoria auditavel.',
      'Use providers externos apenas quando precisar de busca, embeddings ou memoria fora da CongChain.',
    ],
    safety:
      'Memoria nao deve armazenar secrets, private keys, seed phrases, signed payloads ou dados que possam mover fundos.',
  },
  {
    id: 'llm',
    label: 'LLM providers',
    count: 28,
    headline: 'Modelos que o Mythos pode usar para pensar e executar tarefas.',
    explanation:
      'Providers de LLM sao conectores para modelos diferentes. Eles permitem escolher o melhor motor para custo, velocidade, raciocinio, codigo, visao ou contexto longo.',
    items: [
      'OpenAI',
      'Anthropic',
      'Google Gemini',
      'DeepSeek',
      'Mistral',
      'Groq',
      'Together',
      'Fireworks',
      'OpenRouter',
      'xAI',
      'Z.ai',
      'NVIDIA',
      'MiniMax',
      'Qwen',
      'Cohere',
      'Perplexity',
      'Azure OpenAI',
      'AWS Bedrock',
      'Vertex AI',
      'Ollama local',
    ],
    howToUse: [
      'Escolha o provider pelo tipo de tarefa: codigo, pesquisa, custo, velocidade ou contexto.',
      'Adicione a API key do provider no ambiente do Mythos.',
      'Defina um modelo padrao para o agente.',
      'Use a CongChain para registrar qual modelo gerou cada memoria importante.',
    ],
    safety:
      'Providers podem exigir chaves pagas. Nunca cole API keys dentro de memorias, prompts publicos ou resultados salvos.',
  },
  {
    id: 'platforms',
    label: 'Plataformas',
    count: 19,
    headline: 'Canais onde o Mythos pode conversar ou receber trabalho.',
    explanation:
      'Plataformas sao adaptadores de mensagem. Elas permitem ligar o agente a chats, comunidades, automacoes e interfaces externas.',
    items: [
      'Discord',
      'Telegram',
      'Slack',
      'WhatsApp',
      'Matrix',
      'X/Twitter',
      'Reddit',
      'GitHub',
      'Email',
      'Web chat',
      'CLI',
      'QQBot',
      'Teams',
      'Google Chat',
      'IRC',
      'LINE',
      'SimpleX',
      'MS Graph',
      'Webhook',
    ],
    howToUse: [
      'Escolha uma plataforma onde o agente vai operar.',
      'Configure token/bot credentials dessa plataforma no runtime do Mythos.',
      'Defina quais eventos podem virar memoria CongChain.',
      'Comece em modo leitura ou teste antes de permitir respostas automaticas.',
    ],
    safety:
      'Canais externos devem ter permissao minima. A CongChain registra contexto, mas nao deve expor tokens de bots nem conversas sensiveis sem consentimento.',
  },
  {
    id: 'lsp',
    label: 'LSPs',
    count: 26,
    headline: 'Leitura inteligente de codigo por linguagem.',
    explanation:
      'LSPs sao servidores de linguagem. Eles ajudam o Mythos a entender simbolos, erros, referencias, tipos e estrutura de codigo antes de sugerir alteracoes.',
    items: [
      'Python',
      'TypeScript',
      'Go',
      'Rust',
      'C/C++',
      'Bash',
      'YAML',
      'Lua',
      'PHP',
      'OCaml',
      'Dockerfile',
      'Terraform',
      'Dart',
      'Haskell',
      'Julia',
      'Clojure',
      'Nix',
      'Zig',
      'Gleam',
      'Elixir',
      'Prisma',
      'Kotlin',
      'Java',
      'Vue',
      'Svelte',
      'Astro',
    ],
    howToUse: [
      'Abra um projeto no Mythos.',
      'Deixe o LSP da linguagem detectar simbolos e diagnosticos.',
      'Use skills de codigo para planejar, testar e revisar.',
      'Salve decisoes importantes na CongChain quando houver handoff tecnico.',
    ],
    safety:
      'LSP entende codigo, mas nao deve executar comandos destrutivos sem revisao humana.',
  },
  {
    id: 'tools',
    label: 'Tool files',
    count: 76,
    headline: 'Ferramentas internas que expandem o que o agente consegue fazer.',
    explanation:
      'Tool files incluem helpers, conectores, adaptadores e utilitarios. Nem todo arquivo vira uma ferramenta direta para o modelo, mas todos fazem parte do kit operacional.',
    items: [
      'Terminal controlado',
      'Leitura de arquivos',
      'Busca em repo',
      'Web search',
      'Browser tools',
      'Git helpers',
      'Kanban',
      'Dashboards',
      'Observability',
      'Image generation',
      'Video generation',
      'Google Meet',
      'Spotify',
      'Disk cleanup',
      'Context engine',
      'Model routing',
    ],
    howToUse: [
      'Escolha a skill primeiro.',
      'A skill orienta quais ferramentas devem ser usadas.',
      'O Mythos executa ferramentas conforme permissao do ambiente.',
      'Resultados relevantes podem virar memoria verificavel na CongChain.',
    ],
    safety:
      'Ferramentas com escrita, rede, automacao ou limpeza precisam de limites claros e permissao explicita.',
  },
] as const;

export const MYTHOS_FEATURED_SKILLS = [
  {
    id: 'congchain-memory',
    name: 'CongChain Memory Bridge',
    category: 'congchain',
    path: 'optional-skills/blockchain/congchain',
    status: 'pronta para key',
    level: 'oficial',
    useCase:
      'Salvar memoria do Mythos na CongChain com hash, owner, vault isolado e bloqueio contra secrets.',
    bestFor: 'Quando o agente externo precisa registrar contexto verificavel.',
    command: 'mythos skill use optional-skills/blockchain/congchain',
  },
  {
    id: 'congchain-forge',
    name: 'CongChain Forge',
    category: 'congchain',
    path: 'skills/software-development/congchain-forge',
    status: 'pronta',
    level: 'oficial',
    useCase:
      'Criar planos tecnicos e registrar decisoes de desenvolvimento conectadas ao vault CongChain.',
    bestFor: 'Quando o Mythos vai ajudar em codigo, arquitetura ou handoff tecnico.',
    command: 'mythos skill use skills/software-development/congchain-forge',
  },
  {
    id: 'systematic-debugging',
    name: 'Systematic Debugging',
    category: 'development',
    path: 'skills/software-development/systematic-debugging',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Diagnosticar bugs por hipotese, evidencia, teste minimo e correcao rastreavel.',
    bestFor: 'Quando algo quebrou e precisa de investigacao sem chute.',
    command: 'mythos skill use skills/software-development/systematic-debugging',
  },
  {
    id: 'codebase-inspection',
    name: 'Codebase Inspection',
    category: 'development',
    path: 'skills/github/codebase-inspection',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Ler estrutura de repo, localizar fluxos importantes e responder com referencias tecnicas.',
    bestFor: 'Antes de alterar um projeto grande ou desconhecido.',
    command: 'mythos skill use skills/github/codebase-inspection',
  },
  {
    id: 'test-driven-development',
    name: 'Test Driven Development',
    category: 'development',
    path: 'skills/software-development/test-driven-development',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Transformar requisito em teste, implementar e validar mudancas com menor risco.',
    bestFor: 'Features sensiveis ou refactors que nao podem quebrar comportamento.',
    command: 'mythos skill use skills/software-development/test-driven-development',
  },
  {
    id: 'rest-graphql-debug',
    name: 'REST / GraphQL Debug',
    category: 'development',
    path: 'optional-skills/software-development/rest-graphql-debug',
    status: 'opcional',
    level: 'optional',
    useCase:
      'Investigar APIs REST e GraphQL com headers, auth, schemas, erros e contratos.',
    bestFor: 'Quando uma integracao externa retorna 401, 403, 500 ou dados errados.',
    command: 'mythos skill use optional-skills/software-development/rest-graphql-debug',
  },
  {
    id: 'arxiv',
    name: 'Arxiv Research',
    category: 'research',
    path: 'skills/research/arxiv',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Pesquisar papers, resumir contribuicoes e comparar metodos com cuidado.',
    bestFor: 'Pesquisa tecnica e validacao de ideias de IA, cripto ou ciencia.',
    command: 'mythos skill use skills/research/arxiv',
  },
  {
    id: 'domain-intel',
    name: 'Domain Intelligence',
    category: 'research',
    path: 'optional-skills/research/domain-intel',
    status: 'opcional',
    level: 'optional',
    useCase:
      'Analisar dominio, produto, concorrentes, posicionamento e sinais publicos.',
    bestFor: 'Antes de criar narrativa, landing page ou estrategia de mercado.',
    command: 'mythos skill use optional-skills/research/domain-intel',
  },
  {
    id: 'subagent-driven-development',
    name: 'Subagent Driven Development',
    category: 'agent',
    path: 'skills/software-development/subagent-driven-development',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Quebrar trabalho em agentes menores, revisar entregas e integrar resultados.',
    bestFor: 'Quando uma tarefa grande pode ser paralelizada com seguranca.',
    command: 'mythos skill use skills/software-development/subagent-driven-development',
  },
  {
    id: 'openclaw-migration',
    name: 'OpenClaw Migration',
    category: 'agent',
    path: 'optional-skills/migration/openclaw-migration',
    status: 'opcional',
    level: 'optional',
    useCase:
      'Planejar migracao e compatibilidade entre OpenClaw, Mythos e agentes externos.',
    bestFor: 'Quando formos ligar outro agente ao mesmo contrato CongChain.',
    command: 'mythos skill use optional-skills/migration/openclaw-migration',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'productivity',
    path: 'skills/note-taking/obsidian',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Organizar notas, contexto, links e memoria local em formato de vault.',
    bestFor: 'Quando o agente precisa transformar trabalho em conhecimento navegavel.',
    command: 'mythos skill use skills/note-taking/obsidian',
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    category: 'productivity',
    path: 'skills/productivity/google-workspace',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Trabalhar com Docs, Sheets, Drive e materiais de produtividade.',
    bestFor: 'Relatorios, planilhas, handoffs e organizacao operacional.',
    command: 'mythos skill use skills/productivity/google-workspace',
  },
  {
    id: 'evaluation',
    name: 'Model Evaluation',
    category: 'mlops',
    path: 'skills/mlops/evaluation/lm-evaluation-harness',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Avaliar modelos, benchmarks e qualidade de saida com criterios repetiveis.',
    bestFor: 'Comparar providers ou medir melhoria antes de trocar modelo.',
    command: 'mythos skill use skills/mlops/evaluation/lm-evaluation-harness',
  },
  {
    id: 'qdrant',
    name: 'Qdrant Vector Memory',
    category: 'mlops',
    path: 'optional-skills/mlops/qdrant',
    status: 'opcional',
    level: 'optional',
    useCase:
      'Usar banco vetorial para busca semantica, memoria e recuperacao de contexto.',
    bestFor: 'Quando o Mythos precisa recuperar conhecimento por similaridade.',
    command: 'mythos skill use optional-skills/mlops/qdrant',
  },
  {
    id: 'architecture-diagram',
    name: 'Architecture Diagram',
    category: 'media',
    path: 'skills/creative/architecture-diagram',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Transformar arquitetura tecnica em diagrama explicavel e revisavel.',
    bestFor: 'Explicar CongChain, agentes, memory bridge ou fluxo de produto.',
    command: 'mythos skill use skills/creative/architecture-diagram',
  },
  {
    id: 'popular-web-designs',
    name: 'Popular Web Designs',
    category: 'media',
    path: 'skills/creative/popular-web-designs',
    status: 'catalogada',
    level: 'core',
    useCase:
      'Gerar direcao visual e referencias de UI para paginas e dashboards.',
    bestFor: 'Refinar design da pagina Mythos, Marketplace ou Agent Hub.',
    command: 'mythos skill use skills/creative/popular-web-designs',
  },
] as const;

export type MythosSkillCategory = (typeof MYTHOS_SKILL_CATEGORIES)[number];
export type MythosFeaturedSkill = (typeof MYTHOS_FEATURED_SKILLS)[number];
