import { AGENT_MEMORY_BRIDGE_ENDPOINTS } from './types';

export const MYTHOS_AGENT_PROFILE = {
  id: 'mythos',
  name: 'Mythos',
  label: 'First official external agent',
  image: '/agents/mythos.png',
  route: '/mythos',
  summary:
    'External agent structured for context, observability, skills, tasks, and verifiable memory on CongChain.',
  counts: {
    skills: 168,
    memoryProvidersBeforeCongChain: 8,
    memoryProvidersWithCongChain: 9,
    llmProviders: 28,
    messagePlatforms: 19,
    languageServers: 26,
    toolFiles: 76,
  },
  identity: {
    namespace: 'mythos',
    lineage: 'Hermes-compatible fork',
    position: 'Independent CongChain external agent',
    compatibility:
      'Hermes compatibility remains available only as a legacy adapter layer. Mythos writes use source=mythos, contentType=mythos_*, and an isolated Mythos vault by default.',
    evolution:
      'The next identity phase can replace inherited Hermes naming with Mythos-native runtime, docs, skills, and distribution without changing the CongChain bridge contract.',
  },
  contracts: [
    {
      name: 'Context Engine',
      status: 'key adapter ready',
      detail:
        'Selects high-value turns before compression and stores them as authenticated Mythos memory.',
    },
    {
      name: 'Observability',
      status: 'key adapter ready',
      detail:
        'Records tool calls, sessions, and task results as an auditable trail without secrets.',
    },
    {
      name: 'Blockchain Skill',
      status: 'compat ready',
      detail:
        'The legacy vault contract is replaced by Authorization Bearer cog_live_* for production use.'
    },
    {
      name: 'Identity Separation',
      status: 'mythos namespace',
      detail:
        'Inherited Hermes behavior is documented as compatibility only; the active agent identity, vault, source, and content types are Mythos-native.',
    },
  ],
  endpoints: {
    health: AGENT_MEMORY_BRIDGE_ENDPOINTS.health,
    writeMemory: AGENT_MEMORY_BRIDGE_ENDPOINTS.writeMemory,
    listMemories: AGENT_MEMORY_BRIDGE_ENDPOINTS.listMemories,
    verifyMemory: AGENT_MEMORY_BRIDGE_ENDPOINTS.verifyMemory,
    readMemory: AGENT_MEMORY_BRIDGE_ENDPOINTS.readMemory,
    readProof: AGENT_MEMORY_BRIDGE_ENDPOINTS.readProof,
  },
  requiredEnv: [
    {
      name: 'CONGCHAIN_API_URL',
      value: 'https://cognchain-program-production.up.railway.app',
      secret: false,
    },
    {
      name: 'CONGCHAIN_API_KEY',
      value: 'cog_live_...',
      secret: true,
    },
    {
      name: 'CONGCHAIN_AGENT_ID',
      value: 'mythos-local',
      secret: false,
    },
  ],
  safety: [
    'The key authenticates reads and writes for the external agent vault.',
    'Content containing API keys, secrets, private keys, or signed payloads is blocked.',
    'Saved memory does not sign, schedule, buy, sell, or move funds.',
    'On-chain/ZK states are explicit and only appear active when really persisted.',
    'Hermes-compatible code paths must not write into the Mythos vault unless source=mythos is explicitly selected.',
  ],
} as const;

export type MythosAgentProfile = typeof MYTHOS_AGENT_PROFILE;

export const MYTHOS_SKILL_CATEGORIES = [
  {
    id: 'congchain',
    label: 'CongChain',
    count: 18,
    summary: 'Official skills for verifiable memory, audit, bridge workflows, and safe Solana review.',
  },
  {
    id: 'development',
    label: 'Dev',
    count: 18,
    summary: 'Code, debugging, tests, PRs, APIs, and repository review.',
  },
  {
    id: 'research',
    label: 'Research',
    count: 13,
    summary: 'Research, papers, search, OSINT, and domain intelligence.',
  },
  {
    id: 'agent',
    label: 'Agents',
    count: 7,
    summary: 'Orchestration, subagents, Codex, Mythos, and migrations.',
  },
  {
    id: 'mlops',
    label: 'MLOps',
    count: 39,
    summary: 'Models, inference, evaluation, vectors, and fine-tuning.',
  },
  {
    id: 'productivity',
    label: 'Productivity',
    count: 18,
    summary: 'Docs, notes, workspace, PDF, presentations, and automation.',
  },
  {
    id: 'media',
    label: 'Creative',
    count: 22,
    summary: 'Design, images, video, music, diagrams, and content.',
  },
] as const;

export const MYTHOS_CAPABILITY_GROUPS = [
  {
    id: 'memory',
    label: 'Memory providers',
    count: 9,
    headline: 'Where Mythos can store and retrieve context.',
    explanation:
      'Memory providers connect the agent to history, embeddings, vaults, and verifiable memory. CongChain acts as the verifiable/on-chain-ready provider, separate from traditional memory systems.',
    items: [
      'CongChain',
      'byterover',
      'hindsight',
      'holographic',
      'honcho',
      'mem0',
      'openviking',
      'retaindb',
      'supermemory',
    ],
    howToUse: [
      'Create a key in API Keys.',
      'Set CONGCHAIN_API_KEY in the Mythos environment.',
      'Enable the CongChain provider to save auditable memory.',
      'Use external providers only when you need search, embeddings, or memory outside CongChain.',
    ],
    safety:
      'Memory must not store secrets, private keys, seed phrases, signed payloads, or data that can move funds.',
  },
  {
    id: 'llm',
    label: 'LLM providers',
    count: 28,
    headline: 'Models Mythos can use to reason and execute tasks.',
    explanation:
      'LLM providers are connectors to different model backends. They let Mythos choose the best engine for cost, speed, reasoning, code, vision, or long context.',
    items: [
      'OpenAI',
      'Anthropic',
      'Google Gemini',
      'DeepSeek',
      'Mistral',
      'Groq',
      'Together',
      'Fireworks',
      'OpenRouter',
      'xAI',
      'Z.ai',
      'NVIDIA',
      'MiniMax',
      'Qwen',
      'Cohere',
      'Perplexity',
      'Azure OpenAI',
      'AWS Bedrock',
      'Vertex AI',
      'Ollama local',
    ],
    howToUse: [
      'Choose the provider by task type: code, research, cost, speed, or context.',
      'Add the provider API key to the Mythos environment.',
      'Set a default model for the agent.',
      'Use CongChain to record which model generated each important memory.',
    ],
    safety:
      'Providers may require paid keys. Never paste API keys into memories, public prompts, or saved outputs.',
  },
  {
    id: 'platforms',
    label: 'Platforms',
    count: 19,
    headline: 'Channels where Mythos can talk or receive work.',
    explanation:
      'Platforms are message adapters. They connect the agent to chats, communities, automations, and external interfaces.',
    items: [
      'Discord',
      'Telegram',
      'Slack',
      'WhatsApp',
      'Matrix',
      'X/Twitter',
      'Reddit',
      'GitHub',
      'Email',
      'Web chat',
      'CLI',
      'QQBot',
      'Teams',
      'Google Chat',
      'IRC',
      'LINE',
      'SimpleX',
      'MS Graph',
      'Webhook',
    ],
    howToUse: [
      'Choose the platform where the agent will operate.',
      'Configure that platform token or bot credentials in the Mythos runtime.',
      'Define which events may become CongChain memory.',
      'Start in read-only or test mode before allowing automatic replies.',
    ],
    safety:
      'External channels should use minimum permissions. CongChain records context, but must not expose bot tokens or sensitive conversations without consent.',
  },
  {
    id: 'lsp',
    label: 'LSPs',
    count: 26,
    headline: 'Language-aware code understanding.',
    explanation:
      'LSPs are language servers. They help Mythos understand symbols, errors, references, types, and code structure before suggesting changes.',
    items: [
      'Python',
      'TypeScript',
      'Go',
      'Rust',
      'C/C++',
      'Bash',
      'YAML',
      'Lua',
      'PHP',
      'OCaml',
      'Dockerfile',
      'Terraform',
      'Dart',
      'Haskell',
      'Julia',
      'Clojure',
      'Nix',
      'Zig',
      'Gleam',
      'Elixir',
      'Prisma',
      'Kotlin',
      'Java',
      'Vue',
      'Svelte',
      'Astro',
    ],
    howToUse: [
      'Open a project in Mythos.',
      'Let the language server detect symbols and diagnostics.',
      'Use code skills to plan, test, and review.',
      'Save important decisions to CongChain when there is technical handoff.',
    ],
    safety:
      'LSPs understand code, but destructive commands still require human review.',
  },
  {
    id: 'tools',
    label: 'Tool files',
    count: 76,
    headline: 'Internal tools that expand what the agent can do.',
    explanation:
      'Tool files include helpers, connectors, adapters, and utilities. Not every file is exposed directly to the model, but all of them are part of the operational kit.',
    items: [
      'Terminal controlado',
      'Leitura de arquivos',
      'Busca em repo',
      'Web search',
      'Browser tools',
      'Git helpers',
      'Kanban',
      'Dashboards',
      'Observability',
      'Image generation',
      'Video generation',
      'Google Meet',
      'Spotify',
      'Disk cleanup',
      'Context engine',
      'Model routing',
    ],
    howToUse: [
      'Choose the skill first.',
      'The skill guides which tools should be used.',
      'Mythos runs tools according to the environment permissions.',
      'Relevant results can become verifiable memory in CongChain.',
    ],
    safety:
      'Tools with write, network, automation, or cleanup powers need clear limits and explicit permission.',
  },
] as const;

export const MYTHOS_READINESS_ITEMS = [
  {
    id: 'runtime',
    label: 'Mythos runtime',
    state: 'ready',
    signal: 'Local Mythos runtime can run terminal, skills, planning, memory, browser, web, image/video, and messaging when configured.',
    setup: 'Run `mythos doctor` in the Mythos environment before real tasks.',
    safety: 'Runtime tools still follow local permissions and user approval.',
  },
  {
    id: 'bridge',
    label: 'CongChain bridge',
    state: 'live',
    signal: 'The public bridge health endpoint confirms service availability when online.',
    setup: 'Use `/api/memory/health` and a `cog_live_*` key for authenticated writes.',
    safety: 'Writes require Authorization Bearer key; health alone does not prove write access.',
  },
  {
    id: 'memory-write',
    label: 'Verifiable memory write',
    state: 'configured',
    signal: 'Mythos can write safe metadata through `/api/memory/write` with source `mythos` and isolated vault metadata.',
    setup: 'Set `CONGCHAIN_API_KEY` and `CONGCHAIN_AGENT_ID` in the Mythos environment.',
    safety: 'Secrets, private keys, signed payloads, and fund-moving data must be blocked.',
  },
  {
    id: 'skills',
    label: 'Skill-governed execution',
    state: 'ready',
    signal: 'The Mythos page now exposes CongChain governance, Solana review, routing, dev, research, and creative skills.',
    setup: 'Choose a skill before sending complex work to Mythos.',
    safety: 'Selecting a skill does not execute it automatically.',
  },
  {
    id: 'web',
    label: 'Web search and extraction',
    state: 'configured',
    signal: 'Available when `TAVILY_API_KEY`, `EXA_API_KEY`, Firecrawl, Parallel, or another supported web provider is configured.',
    setup: 'Keep at least one web provider key in Mythos `.env`.',
    safety: 'Web evidence needs source review and date awareness.',
  },
  {
    id: 'browser',
    label: 'Browser automation',
    state: 'configured',
    signal: 'Available when `agent-browser` and Playwright/Chromium are installed.',
    setup: 'Use browser tools for visible web workflows and inspect results before saving memory.',
    safety: 'Do not automate logins, purchases, transfers, or destructive account actions without explicit approval.',
  },
  {
    id: 'messaging',
    label: 'Telegram and Discord gateway',
    state: 'configured',
    signal: 'Messaging works when platform tokens and allowlists are configured in Mythos gateway.',
    setup: 'Run `mythos gateway run` after configuring `TELEGRAM_BOT_TOKEN` or `DISCORD_BOT_TOKEN`.',
    safety: 'Use allowlists; never expose bot tokens in memory or screenshots.',
  },
  {
    id: 'media',
    label: 'Image and video generation',
    state: 'configured',
    signal: 'Available when FAL/OpenAI or other supported media provider keys are present.',
    setup: 'Use `FAL_KEY` or the provider key supported by the Mythos tool.',
    safety: 'Generated media should be labeled as generated and checked before public use.',
  },
  {
    id: 'computer-use',
    label: 'Computer use',
    state: 'blocked',
    signal: 'Full computer-use mode is not available on this Windows setup because the runtime path is macOS-only today.',
    setup: 'Use browser automation and terminal tools here; test computer-use on supported macOS runtime later.',
    safety: 'This is intentionally blocked instead of pretending to be ready.',
  },
  {
    id: 'wallet-funds',
    label: 'Wallet and funds movement',
    state: 'blocked',
    signal: 'Mythos and CongChain memory tools cannot buy, sell, sign, submit, schedule, or move funds automatically.',
    setup: 'Use the Wallet Agent review/signature/submission phases for any future value-moving flow.',
    safety: 'Every value-moving action requires visible user approval and wallet-side signature.',
  },
] as const;

export const MYTHOS_FEATURED_SKILLS = [
  {
    id: 'congchain-memory',
    name: 'CongChain Memory Bridge',
    category: 'congchain',
    path: 'optional-skills/blockchain/congchain',
    status: 'key ready',
    level: 'oficial',
    useCase:
      'Save Mythos memory to CongChain with hash, owner, isolated vault, and secret blocking.',
    bestFor: 'Use when an external agent needs to record verifiable context.',
    command: 'mythos skill use optional-skills/blockchain/congchain',
  },
  {
    id: 'congchain-forge',
    name: 'CongChain Forge',
    category: 'congchain',
    path: 'skills/software-development/congchain-forge',
    status: 'ready',
    level: 'oficial',
    useCase:
      'Create technical plans and record development decisions connected to the CongChain vault.',
    bestFor: 'Use when Mythos helps with code, architecture, or technical handoff.',
    command: 'mythos skill use skills/software-development/congchain-forge',
  },
  {
    id: 'congchain-session-audit',
    name: 'CongChain Session Audit',
    category: 'congchain',
    path: 'skills/congchain/session-audit',
    status: 'governance ready',
    level: 'official',
    useCase:
      'Create a safe audit report with objective, selected skill, model, tools, memory status, and next operator step.',
    bestFor: 'Use when a session needs a clean technical receipt or deployment handoff.',
    command: 'mythos skill use skills/congchain/session-audit',
  },
  {
    id: 'congchain-memory-search',
    name: 'CongChain Memory Search',
    category: 'congchain',
    path: 'skills/congchain/memory-search',
    status: 'vault ready',
    level: 'official',
    useCase:
      'Find Mythos vault records by hash, owner, source, agent ID, content type, tags, or safe summary.',
    bestFor: 'Use when the user wants to resume prior work without knowing the exact memory hash.',
    command: 'mythos skill use skills/congchain/memory-search',
  },
  {
    id: 'congchain-context-diff',
    name: 'CongChain Context Diff',
    category: 'congchain',
    path: 'skills/congchain/context-diff',
    status: 'review helper',
    level: 'official',
    useCase:
      'Compare two sessions or memory records and explain visible changes in skill, model, assumptions, and safety flags.',
    bestFor: 'Use before reusing old context after a model, provider, or task shift.',
    command: 'mythos skill use skills/congchain/context-diff',
  },
  {
    id: 'congchain-forge-lsp',
    name: 'CongChain Forge LSP',
    category: 'congchain',
    path: 'skills/congchain/forge-lsp',
    status: 'dev review',
    level: 'official',
    useCase:
      'Run language-aware checks before trusting a Forge proposal or saving development decisions.',
    bestFor: 'Use when code changes need diagnostics, tests, and safer handoff notes.',
    command: 'mythos skill use skills/congchain/forge-lsp',
  },
  {
    id: 'congchain-vault-bootstrap',
    name: 'CongChain Vault Bootstrap',
    category: 'congchain',
    path: 'skills/congchain/vault-bootstrap',
    status: 'setup ready',
    level: 'official',
    useCase:
      'Guide API URL, API key, agent ID, health check, and optional test write without exposing secrets.',
    bestFor: 'Use when connecting a new Mythos runtime or debugging a 401/403 bridge issue.',
    command: 'mythos skill use skills/congchain/vault-bootstrap',
  },
  {
    id: 'congchain-chain-graph',
    name: 'CongChain Chain Graph',
    category: 'congchain',
    path: 'skills/congchain/chain-graph',
    status: 'provenance ready',
    level: 'official',
    useCase:
      'Build a relationship map between sessions, memories, skills, hashes, proofs, and task results.',
    bestFor: 'Use when an operator needs to see how Mythos knowledge connects over time.',
    command: 'mythos skill use skills/congchain/chain-graph',
  },
  {
    id: 'congchain-confidence-calibration',
    name: 'CongChain Confidence Calibration',
    category: 'congchain',
    path: 'skills/congchain/confidence-calibration',
    status: 'safety ready',
    level: 'official',
    useCase:
      'Label evidence quality and confidence using tool results, memory provenance, inference, and uncertainty.',
    bestFor: 'Use when Mythos must explain how certain it is before a decision or memory write.',
    command: 'mythos skill use skills/congchain/confidence-calibration',
  },
  {
    id: 'congchain-rollback',
    name: 'CongChain Rollback',
    category: 'congchain',
    path: 'skills/congchain/rollback',
    status: 'operator ready',
    level: 'official',
    useCase:
      'Prepare a rollback checklist from git state, session audit, and CongChain memory without reverting automatically.',
    bestFor: 'Use after a risky change, deployment issue, or failed integration test.',
    command: 'mythos skill use skills/congchain/rollback',
  },
  {
    id: 'congchain-multimodel-sync',
    name: 'CongChain Multimodel Sync',
    category: 'congchain',
    path: 'skills/congchain/multimodel-sync',
    status: 'continuity ready',
    level: 'official',
    useCase:
      'Record provider, model, skill, task class, and memory context so work remains portable across models.',
    bestFor: 'Use when routing between NVIDIA, OpenRouter, OpenAI, Mistral, Qwen, GLM, or local models.',
    command: 'mythos skill use skills/congchain/multimodel-sync',
  },
  {
    id: 'congchain-export',
    name: 'CongChain Export',
    category: 'congchain',
    path: 'skills/congchain/export',
    status: 'audit ready',
    level: 'official',
    useCase:
      'Export safe metadata such as hashes, timestamps, source, agent ID, skill, status, proof URLs, and safety flags.',
    bestFor: 'Use for support, internal review, or boardroom audit packets without exposing secrets.',
    command: 'mythos skill use skills/congchain/export',
  },
  {
    id: 'solana-tx-inspector',
    name: 'Solana TX Inspector',
    category: 'congchain',
    path: 'skills/congchain/solana-tx-inspector',
    status: 'read-only',
    level: 'official',
    useCase:
      'Inspect public Solana transaction metadata and explain status, accounts, instructions, fees, and visible risks.',
    bestFor: 'Use when a user wants transaction review without signing or submitting anything.',
    command: 'mythos skill use skills/congchain/solana-tx-inspector',
  },
  {
    id: 'solana-vault-health',
    name: 'Solana Vault Health',
    category: 'congchain',
    path: 'skills/congchain/solana-vault-health',
    status: 'read-only',
    level: 'official',
    useCase:
      'Check public Solana/CongChain vault signals and clearly label whether data came from config, API, or RPC.',
    bestFor: 'Use when a vault or public address needs a safe health review.',
    command: 'mythos skill use skills/congchain/solana-vault-health',
  },
  {
    id: 'solana-airdrop-manager',
    name: 'Solana Airdrop Manager',
    category: 'congchain',
    path: 'skills/congchain/solana-airdrop-manager',
    status: 'devnet only',
    level: 'official',
    useCase:
      'Guide Devnet SOL airdrop troubleshooting, faucet limits, RPC errors, wallet checks, and retry timing.',
    bestFor: 'Use when a test wallet cannot receive Devnet SOL.',
    command: 'mythos skill use skills/congchain/solana-airdrop-manager',
  },
  {
    id: 'solana-anchor-schema-validator',
    name: 'Solana Anchor Schema Validator',
    category: 'congchain',
    path: 'skills/congchain/solana-anchor-schema-validator',
    status: 'review helper',
    level: 'official',
    useCase:
      'Review Anchor IDL, account layout, instruction names, and schema mismatches before migration or deployment.',
    bestFor: 'Use when a CongChain/Solana program interface needs careful review.',
    command: 'mythos skill use skills/congchain/solana-anchor-schema-validator',
  },
  {
    id: 'solana-memory-finality-tracker',
    name: 'Solana Memory Finality Tracker',
    category: 'congchain',
    path: 'skills/congchain/solana-memory-finality-tracker',
    status: 'proof aware',
    level: 'official',
    useCase:
      'Separate local, API-saved, proof-available, anchor-submitted, confirmed, and finalized memory states.',
    bestFor: 'Use when the user asks whether a Mythos memory is actually anchored or only saved.',
    command: 'mythos skill use skills/congchain/solana-memory-finality-tracker',
  },
  {
    id: 'solana-wallet-ecosystem-bridge',
    name: 'Solana Wallet Ecosystem Bridge',
    category: 'congchain',
    path: 'skills/congchain/solana-wallet-ecosystem-bridge',
    status: 'planning only',
    level: 'future-safe',
    useCase:
      'Plan safe future connections to Phantom, Solflare, Helius, Jupiter, and RPC providers while keeping wallet approval explicit.',
    bestFor: 'Use for architecture review before any wallet-signing phase exists.',
    command: 'mythos skill use skills/congchain/solana-wallet-ecosystem-bridge',
  },
  {
    id: 'systematic-debugging',
    name: 'Systematic Debugging',
    category: 'development',
    path: 'skills/software-development/systematic-debugging',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Diagnose bugs through hypotheses, evidence, minimal tests, and traceable fixes.',
    bestFor: 'Use when something broke and needs investigation without guessing.',
    command: 'mythos skill use skills/software-development/systematic-debugging',
  },
  {
    id: 'codebase-inspection',
    name: 'Codebase Inspection',
    category: 'development',
    path: 'skills/github/codebase-inspection',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Read repository structure, locate important flows, and answer with technical references.',
    bestFor: 'Use before changing a large or unfamiliar project.',
    command: 'mythos skill use skills/github/codebase-inspection',
  },
  {
    id: 'test-driven-development',
    name: 'Test Driven Development',
    category: 'development',
    path: 'skills/software-development/test-driven-development',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Turn requirements into tests, implement, and validate changes with lower risk.',
    bestFor: 'Use for sensitive features or refactors that must not break behavior.',
    command: 'mythos skill use skills/software-development/test-driven-development',
  },
  {
    id: 'rest-graphql-debug',
    name: 'REST / GraphQL Debug',
    category: 'development',
    path: 'optional-skills/software-development/rest-graphql-debug',
    status: 'optional',
    level: 'optional',
    useCase:
      'Investigate REST and GraphQL APIs with headers, auth, schemas, errors, and contracts.',
    bestFor: 'Use when an external integration returns 401, 403, 500, or wrong data.',
    command: 'mythos skill use optional-skills/software-development/rest-graphql-debug',
  },
  {
    id: 'arxiv',
    name: 'Arxiv Research',
    category: 'research',
    path: 'skills/research/arxiv',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Search papers, summarize contributions, and compare methods carefully.',
    bestFor: 'Use for technical research and validation of AI, crypto, or science ideas.',
    command: 'mythos skill use skills/research/arxiv',
  },
  {
    id: 'domain-intel',
    name: 'Domain Intelligence',
    category: 'research',
    path: 'optional-skills/research/domain-intel',
    status: 'optional',
    level: 'optional',
    useCase:
      'Analyze domain, product, competitors, positioning, and public signals.',
    bestFor: 'Use before creating narrative, landing pages, or market strategy.',
    command: 'mythos skill use optional-skills/research/domain-intel',
  },
  {
    id: 'subagent-driven-development',
    name: 'Subagent Driven Development',
    category: 'agent',
    path: 'skills/software-development/subagent-driven-development',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Break work into smaller agents, review deliverables, and integrate results.',
    bestFor: 'Use when a large task can be safely parallelized.',
    command: 'mythos skill use skills/software-development/subagent-driven-development',
  },
  {
    id: 'openclaw-migration',
    name: 'OpenClaw Migration',
    category: 'agent',
    path: 'optional-skills/migration/openclaw-migration',
    status: 'optional',
    level: 'optional',
    useCase:
      'Plan migration and compatibility between OpenClaw, Mythos, and external agents.',
    bestFor: 'Use when connecting another agent to the same CongChain contract.',
    command: 'mythos skill use optional-skills/migration/openclaw-migration',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'productivity',
    path: 'skills/note-taking/obsidian',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Organize notes, context, links, and local memory as a vault.',
    bestFor: 'Use when the agent needs to turn work into navigable knowledge.',
    command: 'mythos skill use skills/note-taking/obsidian',
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    category: 'productivity',
    path: 'skills/productivity/google-workspace',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Work with Docs, Sheets, Drive, and productivity materials.',
    bestFor: 'Use for reports, spreadsheets, handoffs, and operational organization.',
    command: 'mythos skill use skills/productivity/google-workspace',
  },
  {
    id: 'evaluation',
    name: 'Model Evaluation',
    category: 'mlops',
    path: 'skills/mlops/evaluation/lm-evaluation-harness',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Evaluate models, benchmarks, and output quality with repeatable criteria.',
    bestFor: 'Use to compare providers or measure improvement before switching models.',
    command: 'mythos skill use skills/mlops/evaluation/lm-evaluation-harness',
  },
  {
    id: 'qdrant',
    name: 'Qdrant Vector Memory',
    category: 'mlops',
    path: 'optional-skills/mlops/qdrant',
    status: 'optional',
    level: 'optional',
    useCase:
      'Use a vector database for semantic search, memory, and context retrieval.',
    bestFor: 'Use when Mythos needs to retrieve knowledge by similarity.',
    command: 'mythos skill use optional-skills/mlops/qdrant',
  },
  {
    id: 'architecture-diagram',
    name: 'Architecture Diagram',
    category: 'media',
    path: 'skills/creative/architecture-diagram',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Turn technical architecture into an explainable and reviewable diagram.',
    bestFor: 'Use to explain CongChain, agents, memory bridge, or product flows.',
    command: 'mythos skill use skills/creative/architecture-diagram',
  },
  {
    id: 'popular-web-designs',
    name: 'Popular Web Designs',
    category: 'media',
    path: 'skills/creative/popular-web-designs',
    status: 'cataloged',
    level: 'core',
    useCase:
      'Generate visual direction and UI references for pages and dashboards.',
    bestFor: 'Use to refine Mythos, Marketplace, or Agent Hub design.',
    command: 'mythos skill use skills/creative/popular-web-designs',
  },
] as const;

export const MYTHOS_CATEGORY_SKILL_INDEX = {
  congchain: [
    'CongChain Memory Bridge',
    'CongChain Forge',
    'CongChain Session Audit',
    'CongChain Memory Search',
    'CongChain Context Diff',
    'CongChain Forge LSP',
    'CongChain Vault Bootstrap',
    'CongChain Chain Graph',
    'CongChain Confidence Calibration',
    'CongChain Rollback',
    'CongChain Multimodel Sync',
    'CongChain Export',
    'Solana TX Inspector',
    'Solana Vault Health',
    'Solana Airdrop Manager',
    'Solana Anchor Schema Validator',
    'Solana Memory Finality Tracker',
    'Solana Wallet Ecosystem Bridge',
  ],
  development: [
    'Systematic Debugging',
    'Codebase Inspection',
    'Test Driven Development',
    'REST / GraphQL Debug',
    'GitHub Code Review',
    'GitHub PR Workflow',
    'GitHub Issues',
    'GitHub Repo Management',
    'Node Inspect Debugger',
    'Python Debugpy',
    'Requesting Code Review',
    'Writing Plans',
    'Spike',
    'Plan',
    'Debugging Mythos TUI Commands',
    'Mythos Agent Skill Authoring',
    'Subagent Driven Development',
    'CongChain Forge',
  ],
  research: [
    'Arxiv Research',
    'Domain Intelligence',
    'Blogwatcher',
    'LLM Wiki',
    'Polymarket',
    'Research Paper Writing',
    'Bioinformatics',
    'Drug Discovery',
    'DuckDuckGo Search',
    'Gitnexus Explorer',
    'OSINT Investigation',
    'Parallel CLI',
    'SearxNG Search',
  ],
  agent: [
    'Subagent Driven Development',
    'Claude Code',
    'Codex',
    'Mythos Agent',
    'OpenCode',
    'Blackbox',
    'OpenClaw Migration',
  ],
  mlops: [
    'Model Evaluation',
    'Weights & Biases',
    'HuggingFace Hub',
    'Llama.cpp',
    'vLLM',
    'Audiocraft',
    'Segment Anything',
    'DSPy',
    'Qdrant Vector Memory',
    'Chroma',
    'FAISS',
    'Pinecone',
    'Guidance',
    'Instructor',
    'LLaVA',
    'Modal',
    'PEFT',
    'PyTorch Lightning',
    'Stable Diffusion',
    'Whisper',
    'Axolotl',
    'TRL Fine-Tuning',
    'Unsloth',
  ],
  productivity: [
    'Obsidian',
    'Google Workspace',
    'Notion',
    'Linear',
    'Airtable',
    'Maps',
    'Nano PDF',
    'OCR and Documents',
    'PowerPoint',
    'Teams Meeting Pipeline',
    'Canvas',
    'Here Now',
    'Memento Flashcards',
    'Shop App',
    'Shopify',
    'SiYuan',
    'Telephony',
    'AgentMail',
  ],
  media: [
    'Architecture Diagram',
    'Popular Web Designs',
    'ASCII Art',
    'ASCII Video',
    'Baoyu Comic',
    'Baoyu Infographic',
    'Claude Design',
    'ComfyUI',
    'Creative Ideation',
    'Design MD',
    'Excalidraw',
    'Humanizer',
    'Manim Video',
    'P5.js',
    'Pixel Art',
    'PreTeXt',
    'Sketch',
    'Songwriting and AI Music',
    'TouchDesigner MCP',
    'Blender MCP',
    'Concept Diagrams',
    'Meme Generation',
  ],
} as const;

export const MYTHOS_UNIQUE_IDENTITY_PILLARS = [
  {
    id: 'provable-memory-passport',
    name: 'Provable Memory Passport',
    signal: 'Every important memory carries source, agent ID, skill context, hash routes, and safety metadata.',
    enterpriseValue:
      'Teams can inspect what the agent remembered, where it came from, and whether it is safe to reuse.',
  },
  {
    id: 'skill-governed-execution',
    name: 'Skill-Governed Execution',
    signal: 'Work starts from a declared skill category instead of an invisible generic prompt.',
    enterpriseValue:
      'Operators can choose the right capability before execution and audit which skill shaped the outcome.',
  },
  {
    id: 'memory-constitution',
    name: 'Memory Constitution',
    signal: 'Anti-secret, no-funds, no-signed-payload, and human-review rules travel with each write.',
    enterpriseValue:
      'Security teams get a readable policy boundary before Mythos becomes part of real workflows.',
  },
  {
    id: 'cross-model-continuity',
    name: 'Cross-Model Continuity',
    signal: 'Mythos can record model, provider, skill, and task context so work can continue across engines.',
    enterpriseValue:
      'Companies can route between model providers without losing the operational memory trail.',
  },
  {
    id: 'external-agent-vault',
    name: 'External Agent Vault',
    signal: 'Each API key, source, and agent ID writes into an isolated logical vault.',
    enterpriseValue:
      'A business can separate Mythos, Hermes, OpenClaw, Eliza, and future agents without mixing records.',
  },
  {
    id: 'boardroom-audit-packet',
    name: 'Boardroom Audit Packet',
    signal: 'The page exposes setup, payload, bridge status, capabilities, and safety posture in one review surface.',
    enterpriseValue:
      'Technical leaders can review the agent as infrastructure, not just as a chat interface.',
  },
] as const;

export const MYTHOS_COGNITIVE_LAYERS = [
  {
    id: 'perception',
    name: 'Perception Layer',
    brainAnalogy: 'Sees signals',
    function:
      'Collects the user request, selected skill, model route, available memory context, and visible system state.',
    auditOutput:
      'What Mythos observed before answering.',
  },
  {
    id: 'memory',
    name: 'Memory Layer',
    brainAnalogy: 'Remembers context',
    function:
      'Separates live prompt context, saved CongChain memory, local Obsidian notes, and external provider memory.',
    auditOutput:
      'Which memory sources were available and which were not used.',
  },
  {
    id: 'reasoning',
    name: 'Reasoning Layer',
    brainAnalogy: 'Explains why',
    function:
      'Connects observations to a chosen skill, evaluates alternatives, and states why a path was selected.',
    auditOutput:
      'Decision rationale, rejected paths, confidence, and assumptions.',
  },
  {
    id: 'prediction',
    name: 'Prediction Layer',
    brainAnalogy: 'Simulates next states',
    function:
      'Projects likely outcomes, risks, and next actions before Mythos recommends a step.',
    auditOutput:
      'Short forecast with uncertainty and risk labels.',
  },
  {
    id: 'conscience',
    name: 'Operational Conscience',
    brainAnalogy: 'Knows limits',
    function:
      'Applies no-secrets, no-funds, no-signed-payloads, and human-review boundaries before action.',
    auditOutput:
      'Safety gates and actions Mythos must not perform automatically.',
  },
  {
    id: 'learning',
    name: 'Auditable Learning Layer',
    brainAnalogy: 'Learns with receipts',
    function:
      'Turns important decisions into reviewable memory only when the user or integration explicitly writes it.',
    auditOutput:
      'Memory candidate, write status, hash route, and review requirements.',
  },
] as const;

export const MYTHOS_DECISION_TRACE_SCHEMA = {
  id: 'mythos_decision_trace_v1',
  version: '1.0.0',
  requiredFields: [
    'perception',
    'memoryContext',
    'selectedSkill',
    'reasoningPath',
    'prediction',
    'decision',
    'confidence',
    'safetyBoundary',
    'nextHumanStep',
  ],
  guarantee:
    'The trace explains operational reasoning and limits. It is not hidden chain-of-thought and must not reveal secrets, private prompts, keys, or signed payloads.',
} as const;

export type MythosSkillCategory = (typeof MYTHOS_SKILL_CATEGORIES)[number];
export type MythosFeaturedSkill = (typeof MYTHOS_FEATURED_SKILLS)[number];
export type MythosUniqueIdentityPillar = (typeof MYTHOS_UNIQUE_IDENTITY_PILLARS)[number];
export type MythosCognitiveLayer = (typeof MYTHOS_COGNITIVE_LAYERS)[number];
