'use client';

import { motion } from 'framer-motion';
import { Check, ExternalLink, LockKeyhole, ShieldCheck, Sparkles, WalletCards } from 'lucide-react';
import type { ForgePhase } from '@/lib/forge/types';

export function ForgePreview({ phase }: { phase: ForgePhase }) {
  const active = ['building', 'deploying', 'complete'].includes(phase);
  const progressByPhase: Record<ForgePhase, number> = {
    idle: 8,
    thinking: 18,
    planning: 34,
    building: 64,
    deploying: 86,
    complete: 100,
    error: 18,
  };
  const statusLabel: Record<ForgePhase, string> = {
    idle: 'Waiting for prompt',
    thinking: 'Reading intent',
    planning: 'Architecting PrivatePay',
    building: 'Generating interface',
    deploying: 'Preparing proof capsule',
    complete: 'Receipt layer ready',
    error: 'Recovery needed',
  };
  const proofSteps = [
    { label: 'Intent encrypted', ready: ['building', 'deploying', 'complete'].includes(phase) },
    { label: 'Receipt proof derived', ready: ['deploying', 'complete'].includes(phase) },
    { label: 'Solana anchor ready', ready: phase === 'complete' },
  ];

  return (
    <div className="h-full min-h-[430px] overflow-hidden bg-[#050505]">
      <div className="flex items-center gap-1.5 border-b border-white/[0.07] px-3 py-2">
        <span className="size-2.5 rounded-full bg-red-400/70" />
        <span className="size-2.5 rounded-full bg-yellow-400/70" />
        <span className="size-2.5 rounded-full bg-[#14F195]/70" />
        <span className="ml-2 truncate rounded-full border border-white/[0.07] bg-white/[0.035] px-3 py-1 text-[11px] text-white/35">
          forge-preview.local
        </span>
      </div>

      <div className="relative h-[calc(100%-40px)] overflow-hidden p-5">
        <div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-[#9945FF]/15 blur-3xl" />
        <div className="absolute bottom-0 left-0 h-44 w-44 rounded-full bg-[#14F195]/10 blur-3xl" />
        <div className="absolute left-1/2 top-10 h-56 w-56 -translate-x-1/2 rounded-full bg-[#38BDF8]/10 blur-3xl" />

        <motion.div
          className="relative h-full overflow-hidden rounded-3xl border border-white/[0.08] bg-[#09090B]/92 p-5 shadow-2xl shadow-black/40"
          animate={{ y: active ? [0, -4, 0] : 0 }}
          transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
        >
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_18%,rgba(153,69,255,0.20),transparent_34%),radial-gradient(circle_at_14%_74%,rgba(20,241,149,0.12),transparent_28%)]" />

          <div className="relative flex h-full min-h-0 flex-col">
            <div className="flex items-center justify-between gap-4">
              <div className="min-w-0">
                <p className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#14F195]/75">PrivatePay Preview</p>
                <h3 className="mt-2 max-w-lg text-3xl font-semibold leading-tight text-white">
                  Private payments for Solana teams.
                </h3>
                <p className="mt-2 max-w-xl text-sm leading-6 text-white/46">
                  Encrypted payment intents, receipt proofs, and a clean checkout surface generated by the Forge agents.
                </p>
              </div>
              <button className="shrink-0 rounded-full border border-white/[0.08] bg-white/[0.04] p-2 text-white/40">
                <ExternalLink className="size-4" />
              </button>
            </div>

            <div className="mt-5 grid min-h-0 flex-1 gap-4 lg:grid-cols-[1.05fr_0.95fr]">
              <div className="flex min-h-0 flex-col rounded-2xl border border-white/[0.07] bg-black/30 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="grid size-8 place-items-center rounded-xl bg-[#9945FF]/15 text-[#C084FC]">
                      <LockKeyhole className="size-4" />
                    </span>
                    <div>
                      <p className="text-[11px] font-medium uppercase tracking-[0.18em] text-white/30">Transfer intent</p>
                      <p className="text-sm font-semibold text-white/78">Encrypted checkout</p>
                    </div>
                  </div>
                  <span className="rounded-full border border-[#14F195]/20 bg-[#14F195]/10 px-2.5 py-1 text-[10px] font-semibold text-[#14F195]">
                    {statusLabel[phase]}
                  </span>
                </div>

                <div className="mt-5 space-y-3">
                  {[
                    ['Recipient', '7xP4...9kL2'],
                    ['Amount', '2.40 SOL'],
                    ['Private memo', phase === 'complete' ? 'sealed and hashed' : 'encrypting'],
                  ].map(([label, value]) => (
                    <div key={label} className="rounded-2xl border border-white/[0.06] bg-white/[0.035] p-3">
                      <p className="text-[10px] uppercase tracking-[0.16em] text-white/28">{label}</p>
                      <p className="mt-1 font-mono text-sm text-white/72">{value}</p>
                    </div>
                  ))}
                </div>

                <div className="mt-auto pt-4">
                  <div className="h-1.5 overflow-hidden rounded-full bg-white/[0.07]">
                    <motion.div
                      className="h-full rounded-full bg-gradient-to-r from-[#9945FF] via-[#38BDF8] to-[#14F195]"
                      animate={{ width: `${progressByPhase[phase]}%` }}
                      transition={{ duration: 0.55, ease: 'easeOut' }}
                    />
                  </div>
                  <button className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl border border-[#14F195]/25 bg-[#14F195]/12 px-4 py-3 text-sm font-semibold text-[#D8FFF0]">
                    <WalletCards className="size-4" />
                    {phase === 'complete' ? 'Receipt proof ready' : 'Generate private receipt'}
                  </button>
                </div>
              </div>

              <div className="flex min-h-0 flex-col gap-3">
                <div className="rounded-2xl border border-white/[0.07] bg-white/[0.035] p-4">
                  <div className="flex items-center gap-2">
                    <ShieldCheck className="size-4 text-[#14F195]" />
                    <p className="text-sm font-semibold text-white/78">Proof rail</p>
                  </div>
                  <div className="mt-4 space-y-3">
                    {proofSteps.map(step => (
                      <div key={step.label} className="flex items-center justify-between gap-3 rounded-xl border border-white/[0.06] bg-black/24 px-3 py-2">
                        <span className="text-xs text-white/55">{step.label}</span>
                        <span className={step.ready ? 'text-[#14F195]' : 'text-white/20'}>
                          {step.ready ? <Check className="size-4" /> : <span className="block size-2 rounded-full border border-current" />}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="min-h-0 flex-1 rounded-2xl border border-[#9945FF]/15 bg-[#9945FF]/[0.05] p-4">
                  <div className="flex items-center gap-2">
                    <Sparkles className="size-4 text-[#C084FC]" />
                    <p className="text-sm font-semibold text-white/80">Live build</p>
                  </div>
                  <p className="mt-3 text-sm leading-6 text-white/48">
                    {phase === 'complete'
                      ? 'Forge assembled the PrivatePay interface, typed intent route, and Solana receipt proof capsule inside the sandbox.'
                      : 'Agents are constructing the product surface live: interface first, then API contract, then privacy proof status.'}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
