import type { ForgeAgent, ForgeBuildStep, ForgeFile, ForgeMemoryNode, ForgeTerminalLine } from './types';

export const FORGE_STORAGE_KEY = 'congchain_forge_session_v1';

export const forgeAgents: ForgeAgent[] = [
  {
    id: 'architect',
    name: 'Architect Agent',
    role: 'System design',
    accent: '#9945FF',
    status: 'idle',
    progress: 14,
    currentTask: 'Mapping project intent',
    logs: ['Waiting for a build prompt'],
  },
  {
    id: 'solana',
    name: 'Solana Agent',
    role: 'Programs and proofs',
    accent: '#14F195',
    status: 'idle',
    progress: 8,
    currentTask: 'Monitoring devnet patterns',
    logs: ['Proof layer on standby'],
  },
  {
    id: 'backend',
    name: 'Backend Agent',
    role: 'APIs and data',
    accent: '#38BDF8',
    status: 'idle',
    progress: 12,
    currentTask: 'Preparing service graph',
    logs: ['API sandbox initialized'],
  },
  {
    id: 'ui',
    name: 'UI Agent',
    role: 'Interface craft',
    accent: '#C084FC',
    status: 'idle',
    progress: 18,
    currentTask: 'Calibrating design system',
    logs: ['Visual language loaded'],
  },
  {
    id: 'security',
    name: 'Security Agent',
    role: 'Risk and audit',
    accent: '#F59E0B',
    status: 'idle',
    progress: 10,
    currentTask: 'Watching permissions',
    logs: ['Threat model ready'],
  },
];

export const initialTerminalLines: ForgeTerminalLine[] = [
  {
    id: 'boot-1',
    kind: 'system',
    source: 'Forge Kernel',
    text: 'CongChain Forge sandbox online. No production systems attached.',
    timestamp: 'now',
  },
  {
    id: 'boot-2',
    kind: 'shell',
    source: 'forge.os',
    text: 'agent mesh: architect, solana, backend, ui, security',
    timestamp: 'now',
  },
  {
    id: 'boot-3',
    kind: 'success',
    source: 'Memory Core',
    text: 'Session memory visualization ready for simulated build context.',
    timestamp: 'now',
  },
];

export const initialFiles: ForgeFile[] = [
  {
    path: 'app/page.tsx',
    language: 'tsx',
    status: 'queued',
    contents: `export default function App() {
  return (
    <main className="min-h-screen bg-black text-white">
      <section className="mx-auto max-w-5xl px-6 py-24">
        <p className="text-sm text-emerald-300">Generated by CongChain Forge</p>
        <h1 className="mt-4 text-5xl font-semibold">Verifiable AI application</h1>
      </section>
    </main>
  );
}
`,
  },
  {
    path: 'lib/agent-runtime.ts',
    language: 'ts',
    status: 'queued',
    contents: `export type AgentRuntimeStatus = 'queued' | 'thinking' | 'building' | 'verified';

export function createRuntimeTrace(prompt: string) {
  return {
    prompt,
    status: 'verified' satisfies AgentRuntimeStatus,
    memory: 'portable',
  };
}
`,
  },
  {
    path: 'solana/memory-proof.ts',
    language: 'ts',
    status: 'queued',
    contents: `export function deriveMemoryProof(content: string) {
  return {
    network: 'solana-devnet',
    content,
    proof: 'simulated-forge-proof',
  };
}
`,
  },
];

export const initialBuildSteps: ForgeBuildStep[] = [
  { id: 'intent', label: 'Parse product intent', status: 'pending' },
  { id: 'plan', label: 'Coordinate agent plan', status: 'pending' },
  { id: 'files', label: 'Generate files', status: 'pending' },
  { id: 'verify', label: 'Run simulated checks', status: 'pending' },
  { id: 'deploy', label: 'Prepare deploy capsule', status: 'pending' },
];

export const initialMemoryNodes: ForgeMemoryNode[] = [
  { id: 'm1', label: 'Prompt Intent', detail: 'No prompt submitted yet', confidence: 42 },
  { id: 'm2', label: 'Architecture Trace', detail: 'Awaiting agent plan', confidence: 36 },
  { id: 'm3', label: 'Proof Context', detail: 'Solana layer idle', confidence: 31 },
];

export const suggestedPrompts = [
  'Build a Solana staking dashboard with verifiable AI memory',
  'Create an agent marketplace landing app with wallet-aware onboarding',
  'Generate a private memory vault interface with ZK proof status',
];
